#!/bin/bash -x

isPartTime=1
isFullTime=2
maxHoursInMonth=100
empRatePerHr=20
numOfWorkingDays=20
totalEmpHr=0
totalWorkingDays=

function getWorkingHours()
{
     case $randomCheck in
                 $isPartTime )
                       empHrs=4
                  ;;
                 $isFullTime )
                       empHrs=8
                   ;;
                   *)


done

totalSalary="$( getEmpWage $totalEmpHr )"
echo ${dailyWages[@]}               
 
